name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ranjithkumarbandi/react-static .
      - name: Publish image to docker hub
        # run: docker push integrationninjas/react-static:latest   
        run: docker push ranjithkumarbandi/react-static:latest

  deploy: 
    needs: build
    runs-on: ip-172-31-22-31
    steps:
      - name: Pull image from docker hub
        # run: docker pull integrationninjas/react-static:latest 
        run: docker pull ranjithkumarbandi/react-static:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer ranjithkumarbandi/react-static  